title: MatSE580 Guest Lectures
description: Two guest lectures for MatSE580 at PSU to cover basics of (1) materials data manipulation, (2) storage, and (3) running ML methods on them.
show_downloads: "true"
markdown: GFM

remote_theme: Bilal2453/cayman-docs
plugins:
- jekyll-remote-theme 
